Frozen autocommit 2024-02-09 06:15:35.564054

diff --git a/dkms.in b/dkms.in
--- a/dkms.in
+++ b/dkms.in
@@ -56,7 +56,7 @@ _get_kernel_dir() {
     if [[ -z $ksourcedir_fromcli ]]; then
         KVER=$1
         case ${current_os} in
-           Linux)          DIR="/lib/modules/$KVER/build" ;;
+           Linux)          DIR="$install_tree/$KVER/build" ;;
            GNU/kFreeBSD)   DIR="/usr/src/kfreebsd-headers-$KVER/sys" ;;
         esac
         echo $DIR
@@ -238,9 +238,9 @@ set_module_suffix()
     # $1 = the kernel to base the module_suffix on
     kernel_test="${1:-$(uname -r)}"
     module_uncompressed_suffix=".ko"
-    grep -q '\.gz:' /lib/modules/$kernel_test/modules.dep 2>/dev/null && module_compressed_suffix=".gz"
-    grep -q '\.xz:' /lib/modules/$kernel_test/modules.dep 2>/dev/null && module_compressed_suffix=".xz"
-    grep -q '\.zst:' /lib/modules/$kernel_test/modules.dep 2>/dev/null && module_compressed_suffix=".zst"
+    grep -q '\.gz:' $install_tree/$kernel_test/modules.dep 2>/dev/null && module_compressed_suffix=".gz"
+    grep -q '\.xz:' $install_tree/$kernel_test/modules.dep 2>/dev/null && module_compressed_suffix=".xz"
+    grep -q '\.zst:' $install_tree/$kernel_test/modules.dep 2>/dev/null && module_compressed_suffix=".zst"
     module_suffix="$module_uncompressed_suffix$module_compressed_suffix"
 }
 
@@ -296,7 +296,7 @@ setup_kernels_arches()
             kernelver[0]=$(uname -r)
         fi
         if [[ ! $arch ]]; then
-            kernelver_rpm=$(rpm -qf "/lib/modules/$kernelver" 2>/dev/null | \
+            kernelver_rpm=$(rpm -qf "$install_tree/$kernelver" 2>/dev/null | \
             grep -v "not owned by any package" | grep kernel | head -n 1)
             if ! arch[0]=$(rpm -q --queryformat "%{ARCH}" "$kernelver_rpm" 2>/dev/null); then
                 arch[0]=$(uname -m)
@@ -337,17 +337,23 @@ do_depmod()
     if [[ ${current_os} != Linux ]] ; then
         return
     fi
+    if [[ ! -f $install_tree/$1/modules.dep ]]; then
+        # if the corresponding linux image $1 is not installed
+        # do not create modules.dep
+        echo "Skipping depmod because '$install_tree/$1/modules.dep' is missing."
+        return
+    fi
     if [[ -f /boot/System.map-$1 ]]; then
         depmod -a "$1" -F "/boot/System.map-$1"
     else
         depmod -a "$1"
     fi
-    if [[ -f /lib/modules/$1/modules.dep && ! -s /lib/modules/$1/modules.dep ]]; then
+    if [[ -f $install_tree/$1/modules.dep && ! -s $install_tree/$1/modules.dep ]]; then
         # if modules.dep is empty, we just removed the last kernel module from
         # no longer installed kernel $1, so do not leave stale depmod files around
-        rm -fv /lib/modules/$1/modules.{alias,dep,devname,softdep,symbols,*.bin}
-        rmdir --ignore-fail-on-non-empty /lib/modules/$1
-        [[ -d /lib/modules/$1 ]] || echo $"Removed /lib/modules/$1"
+        rm -fv $install_tree/$1/modules.{alias,dep,devname,softdep,symbols,*.bin}
+        rmdir --ignore-fail-on-non-empty $install_tree/$1
+        [[ -d $install_tree/$1 ]] || echo $"removed directory $install_tree/$1"
     fi
 }
 
@@ -912,7 +918,7 @@ prepare_kernel()
 
     # Check that kernel-source exists
     _check_kernel_dir "$1" || {
-        die 1 $"Your kernel headers for kernel $1 cannot be found at /lib/modules/$1/build or /lib/modules/$1/source." \
+        die 1 $"Your kernel headers for kernel $1 cannot be found at $install_tree/$1/build or $install_tree/$1/source." \
             $"Please install the linux-headers-$1 package or use the --kernelsourcedir option to tell DKMS where it's located."
     }
 }
@@ -949,7 +955,7 @@ prepare_signing()
                 ;;
         esac
         if [[ ! -f ${sign_file} ]]; then
-            sign_file="/lib/modules/$kernelver/build/scripts/sign-file"
+            sign_file="$install_tree/$kernelver/build/scripts/sign-file"
         fi
     fi
     echo "Sign command: $sign_file"
@@ -1603,7 +1609,7 @@ do_uninstall()
     # Run the post_remove script
     run_build_script post_remove "$post_remove"
 
-    # Run depmod because we changed /lib/modules
+    # Run depmod because we changed $install_tree
     invoke_command "do_depmod $1" "depmod" '' background
 
     # Delete the original_module if nothing for this kernel is installed anymore
@@ -2394,7 +2400,7 @@ current_os=$(uname -s)
 running_distribution=$(distro_version) || exit
 dkms_tree="/var/lib/dkms"
 source_tree="/usr/src"
-install_tree="/lib/modules"
+install_tree="@MODDIR@"
 tmp_location=${TMPDIR:-/tmp}
 verbose=""
 symlink_modules=""
@@ -2472,7 +2478,7 @@ while (($# > 0)); do
             exec >/dev/null 2>&1
             ;;
         --version|-V)
-            echo $"#RELEASE_STRING#"
+            echo $"@RELEASE_STRING@"
             exit 0
             ;;
         --no-initrd)
